version: '3.8'
#использовать определенную версию Compose file
services:
#определяет какие сервисы должны быть запущены
  db:
  #название сервиса
    #используемый образ
    image: postgres:latest
    
    # secrets:
    #    - db-password
    ports:
      - 5434:5432
      #порт хоста : порт контейнера
    environment:
    #переменные среды
      POSTGRES_USER: 'denis'
      POSTGRES_PASSWORD: '000111'
      POSTGRES_DB: 'rates'
    volumes:
      #определение скрипта данных
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      #определение хранилища для запуска при создании контейнера
      #- /myvolume:/var/lib/postgresql/data

    healthcheck:
    #проверка состояния контейнера
      test: ["CMD", "pg_isready", "-U", "denis", "000111"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: always
# secrets:
#   db-password:
#     file: db/password.txt 
